---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(highcharter)
library(dplyr)
```

<style>
.titlechart {background-color:peachpuff; padding-left:10px; padding-top:5px; padding-bottom:5px}
</style>

## Performance indicators within the euro area

***
<p style="text-align: right; font-size:75%;">*NACE revision 2; % change*</p>
<p class="titlechart">**Hourly labour cost**; 4-quarterly change *(a)(b)*</p>

```{r}

xl.data <- read_xls(path="../data/zai010b.xls", sheet="Feuil4", range="A2:E34")

c1 <- highchart() %>%
  hc_xAxis(categories=xl.data[,1]) %>%
  hc_add_series(name=names(xl.data)[2],data=xl.data[2]) %>%
  hc_add_series(name=names(xl.data)[3],data=xl.data[3]) %>%
  hc_add_series(name=names(xl.data)[4],data=xl.data[4]) %>%
  hc_add_series(name=names(xl.data)[5],data=xl.data[5])

c1
  
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```


